import type { Metadata } from "next";
import { Geist, Geist_Mono, Hina_Mincho } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header/Header";
import { MenuProvider } from "@/app/provider";
import { FreezeWhileMenuOpen } from "@/components/FreezeWhileMenuOpen";
import { css } from "@panda/css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const hinaMincho = Hina_Mincho({
  variable: "--font-hina-mincho",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "本格麻婆豆腐 乘濵楼",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${hinaMincho.className} ${css({
          backgroundColor: "primary",
        })}`}
      >
        <MenuProvider>
          <FreezeWhileMenuOpen>
            <Header />
            {children}
          </FreezeWhileMenuOpen>
        </MenuProvider>
      </body>
    </html>
  );
}
